#!/usr/bin/env bash

# runtest.sh - Run tests with generated JS files (fully recursive)

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Define paths
TESTS_DIR="${SCRIPT_DIR}/tests"
DUAL_SCRIPT="${SCRIPT_DIR}/dual.sh"

# Color definitions
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
BG_RED='\033[41m'
BG_GREEN='\033[42m'
BG_BLUE='\033[44m'
BG_MAGENTA='\033[45m'
BG_CYAN='\033[46m'

# Check if dual.sh exists
if [[ ! -f "$DUAL_SCRIPT" ]]; then
    echo -e "${RED}${BOLD}Error:${RESET} dual.sh not found at ${DUAL_SCRIPT}"
    exit 1
fi

# Check if tests directory exists
if [[ ! -d "$TESTS_DIR" ]]; then
    echo -e "${RED}${BOLD}Error:${RESET} tests directory not found at ${TESTS_DIR}"
    exit 1
fi

# Arrays to track test results (associative by group path)
declare -A passed_tests
declare -A failed_tests
declare -a group_order

# Function to get relative path from TESTS_DIR
get_group_name() {
    local dir_path="$1"
    local rel_path="${dir_path#$TESTS_DIR}"
    rel_path="${rel_path#/}"
    if [[ -z "$rel_path" ]]; then
        echo "general"
    else
        echo "$rel_path"
    fi
}

# Function to process a test directory recursively
process_test_directory() {
    local dir_path="$1"
    local group_name="$2"
    
    local has_content=false
    
    # Enter the test directory
    cd "$dir_path"
    
    # Get all .sh files sorted numerically
    sh_files=$(ls -1v *.sh 2>/dev/null | grep -E '^[0-9]+\.sh$' || true)
    
    if [[ -n "$sh_files" ]]; then
        has_content=true
        
        if [[ "$group_name" != "general" ]] || [[ -n "$sh_files" ]]; then
            echo -e "${BG_BLUE}${WHITE}${BOLD} Processing test group: ${group_name} ${RESET}"
            echo -e "${DIM}Directory: ${dir_path}${RESET}"
            echo ""
        fi
        
        echo -e "${CYAN}${BOLD}Found test generator scripts:${RESET}"
        echo "$sh_files"
        echo ""
        
        # Execute each .sh file to generate corresponding .js files
        for sh_file in $sh_files; do
            echo -e "${MAGENTA}Executing generator:${RESET} ${BOLD}$sh_file${RESET}"
            bash "$sh_file"
            
            test_num="${sh_file%.sh}"
            
            if [[ ! -f "${test_num}.js" ]]; then
                echo -e "${YELLOW}${BOLD}Warning:${RESET} ${test_num}.js was not generated by ${sh_file}"
            else
                echo -e "${GREEN}Generated:${RESET} ${test_num}.js"
            fi
            echo ""
        done
        
        # Get all generated .js files sorted numerically
        js_files=$(ls -1v *.js 2>/dev/null | grep -E '^[0-9]+\.js$' || true)
        
        if [[ -n "$js_files" ]]; then
            echo -e "${CYAN}${BOLD}Found test files:${RESET}"
            echo "$js_files"
            echo ""
            
            # Execute dual.sh for each .js file in order
            for js_file in $js_files; do
                test_path="${dir_path}/${js_file}"
                test_num="${js_file%.js}"
                
                echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
                echo -e "${WHITE}${BOLD}Running test ${test_num} [${group_name}]:${RESET} dual.sh ${js_file}"
                echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
                
                if bash "$DUAL_SCRIPT" "$test_path"; then
                    echo -e "${BG_GREEN}${WHITE}${BOLD} ✓ Test ${test_num} completed successfully ${RESET}"
                    if [[ -z "${passed_tests[$group_name]}" ]]; then
                        passed_tests["$group_name"]="${test_num}"
                    else
                        passed_tests["$group_name"]="${passed_tests[$group_name]} ${test_num}"
                    fi
                else
                    exit_code=$?
                    echo -e "${BG_RED}${WHITE}${BOLD} ✗ Test ${test_num} failed with exit code: ${exit_code} ${RESET}"
                    if [[ -z "${failed_tests[$group_name]}" ]]; then
                        failed_tests["$group_name"]="${test_num}"
                    else
                        failed_tests["$group_name"]="${failed_tests[$group_name]} ${test_num}"
                    fi
                fi
                echo ""
            done
        fi
    fi
    
    # Now process subdirectories recursively
    if [[ -d "$dir_path" ]]; then
        # Find all immediate subdirectories, sorted alphabetically
        local subdirs=$(find "$dir_path" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | sort)
        
        if [[ -n "$subdirs" ]]; then
            for subdir in $subdirs; do
                local sub_group_name=$(get_group_name "$subdir")
                process_test_directory "$subdir" "$sub_group_name"
            done
        fi
    fi
    
    # Only add to group_order if this group actually had tests
    if [[ -n "${passed_tests[$group_name]}" ]] || [[ -n "${failed_tests[$group_name]}" ]]; then
        group_order+=("$group_name")
    fi
    
    # Return to original directory
    cd "$SCRIPT_DIR"
}

echo -e "${BG_CYAN}${WHITE}${BOLD} Starting test generation and execution phase ${RESET}"
echo ""

# Record overall start time
overall_start=$(date +%s%N)

# Start recursive processing from the root tests directory
process_test_directory "$TESTS_DIR" "general"

# Record overall end time and calculate elapsed
overall_end=$(date +%s%N)
elapsed_ns=$(( overall_end - overall_start ))

echo -e "${BG_CYAN}${WHITE}${BOLD} All tests completed ${RESET}"
echo ""

# Print final summary grouped by test group
echo -e "${BG_MAGENTA}${WHITE}${BOLD}╔══════════════════════════════════════════════════╗${RESET}"
echo -e "${BG_MAGENTA}${WHITE}${BOLD}║              TEST EXECUTION SUMMARY              ║${RESET}"
echo -e "${BG_MAGENTA}${WHITE}${BOLD}╚══════════════════════════════════════════════════╝${RESET}"
echo ""

total_passed=0
total_failed=0
total_tests=0

# Print results only for groups that have test results
if [[ ${#group_order[@]} -gt 0 ]]; then
    for group in "${group_order[@]}"; do
        echo -e "${CYAN}${BOLD}┏━━━ Group: ${group} ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓${RESET}"
        
        # Parse passed tests for this group
        if [[ -n "${passed_tests[$group]}" ]]; then
            passed_array=(${passed_tests[$group]})
            passed_count=${#passed_array[@]}
            total_passed=$((total_passed + passed_count))
            echo -e "${GREEN}${BOLD}✓ PASSED (${passed_count}):${RESET}"
            for test in "${passed_array[@]}"; do
                echo -e "  ${GREEN}•${RESET} Test ${test}"
            done
        else
            echo -e "${GREEN}${BOLD}✓ PASSED (0):${RESET}"
        fi
        
        # Parse failed tests for this group
        if [[ -n "${failed_tests[$group]}" ]]; then
            failed_array=(${failed_tests[$group]})
            failed_count=${#failed_array[@]}
            total_failed=$((total_failed + failed_count))
            echo -e "${RED}${BOLD}✗ FAILED (${failed_count}):${RESET}"
            for test in "${failed_array[@]}"; do
                echo -e "  ${RED}•${RESET} Test ${test}"
            done
        else
            echo -e "${RED}${BOLD}✗ FAILED (0):${RESET}"
        fi
        
        echo ""
    done
else
    echo -e "${YELLOW}${BOLD}No test results to display${RESET}"
    echo ""
fi

# Calculate totals
total_tests=$((total_passed + total_failed))

# Print overall statistics with colors
echo -e "${MAGENTA}${BOLD}┏━━━ Overall Statistics ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓${RESET}"
echo -e "${BOLD}Total groups with tests:${RESET} ${#group_order[@]}"
echo -e "${BOLD}Total tests:${RESET} ${total_tests}"
echo -e "${GREEN}${BOLD}Total passed:${RESET} ${total_passed}"
echo -e "${RED}${BOLD}Total failed:${RESET} ${total_failed}"

# Calculate and display success rate with color coding
if [[ $total_tests -gt 0 ]]; then
    success_rate=$(( (total_passed * 100) / total_tests ))
    
    # Color code the success rate
    if [[ $success_rate -eq 100 ]]; then
        echo -e "Success rate: ${BG_GREEN}${WHITE}${BOLD} ${success_rate}% ${RESET} (${total_passed}/${total_tests} tests passed)"
    elif [[ $success_rate -ge 75 ]]; then
        echo -e "Success rate: ${YELLOW}${BOLD}${success_rate}%${RESET} (${total_passed}/${total_tests} tests passed)"
    else
        echo -e "Success rate: ${RED}${BOLD}${success_rate}%${RESET} (${total_passed}/${total_tests} tests passed)"
    fi
else
    echo -e "Success rate: ${YELLOW}${BOLD}N/A${RESET} (no tests found)"
fi

# Format and display total execution time
if (( elapsed_ns >= 1000000000 )); then
    elapsed_s=$(echo "scale=3; $elapsed_ns / 1000000000" | bc)
    echo -e "${BOLD}Total execution time:${RESET} ${elapsed_s}s"
elif (( elapsed_ns >= 1000000 )); then
    elapsed_ms=$(echo "scale=2; $elapsed_ns / 1000000" | bc)
    echo -e "${BOLD}Total execution time:${RESET} ${elapsed_ms}ms"
else
    elapsed_us=$(echo "scale=2; $elapsed_ns / 1000" | bc)
    echo -e "${BOLD}Total execution time:${RESET} ${elapsed_us}µs"
fi

# Exit with non-zero if any tests failed
if [[ $total_failed -gt 0 ]]; then
    exit 1
fi