#!/usr/bin/env bash

# runtest.sh - Run tests with generated JS files

set -e  # Exit on error

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Define paths
TESTS_DIR="${SCRIPT_DIR}/tests"
DUAL_SCRIPT="${SCRIPT_DIR}/dual.sh"

# Check if dual.sh exists
if [[ ! -f "$DUAL_SCRIPT" ]]; then
    echo "Error: dual.sh not found at ${DUAL_SCRIPT}"
    exit 1
fi

# Check if tests directory exists
if [[ ! -d "$TESTS_DIR" ]]; then
    echo "Error: tests directory not found at ${TESTS_DIR}"
    exit 1
fi

# Arrays to track test results
declare -a passed_tests
declare -a failed_tests

echo "=== Starting test generation phase ==="
echo "Entering tests directory: ${TESTS_DIR}"
cd "$TESTS_DIR"

# Get all .sh files sorted numerically
# Using ls with version sort to handle numeric ordering correctly
sh_files=$(ls -1v *.sh 2>/dev/null | grep -E '^[0-9]+\.sh$' || true)

if [[ -z "$sh_files" ]]; then
    echo "Error: No .sh files found in ${TESTS_DIR}"
    exit 1
fi

echo "Found test generator scripts:"
echo "$sh_files"
echo ""

# Execute each .sh file to generate corresponding .js files
for sh_file in $sh_files; do
    echo "Executing generator: $sh_file"
    bash "$sh_file"
    
    # Extract the number from filename (e.g., "1.sh" -> "1")
    test_num="${sh_file%.sh}"
    
    # Check if the corresponding .js file was generated
    if [[ ! -f "${test_num}.js" ]]; then
        echo "Warning: ${test_num}.js was not generated by ${sh_file}"
    else
        echo "Generated: ${test_num}.js"
    fi
    echo ""
done

echo "=== Test generation phase complete ==="
echo ""

# Return to original directory
cd "$SCRIPT_DIR"

# Get all generated .js files sorted numerically
cd "$TESTS_DIR"
js_files=$(ls -1v *.js 2>/dev/null | grep -E '^[0-9]+\.js$' || true)

if [[ -z "$js_files" ]]; then
    echo "Error: No .js files were generated in ${TESTS_DIR}"
    exit 1
fi

cd "$SCRIPT_DIR"

echo "=== Starting test execution phase ==="
echo "Found test files:"
echo "$js_files"
echo ""

# Execute dual.sh for each .js file in order
for js_file in $js_files; do
    test_path="${TESTS_DIR}/${js_file}"
    test_num="${js_file%.js}"
    
    echo "----------------------------------------"
    echo "Running test ${test_num}: dual.sh ${js_file}"
    echo "----------------------------------------"
    
    # Execute dual.sh with the js file as argument
    if bash "$DUAL_SCRIPT" "$test_path"; then
        echo "✓ Test ${test_num} completed successfully"
        passed_tests+=("${test_num}")
    else
        exit_code=$?
        echo "✗ Test ${test_num} failed with exit code: ${exit_code}"
        failed_tests+=("${test_num}")
    fi
    echo ""
done

echo "=== All tests completed ==="
echo ""

# Print final summary
echo "╔══════════════════════════════════════════════════╗"
echo "║              TEST EXECUTION SUMMARY              ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""

total_tests=$(( ${#passed_tests[@]} + ${#failed_tests[@]} ))

if [[ ${#passed_tests[@]} -gt 0 ]]; then
    echo "✓ PASSED (${#passed_tests[@]}/${total_tests}):"
    for test in "${passed_tests[@]}"; do
        echo "  • Test ${test}"
    done
    echo ""
fi

if [[ ${#failed_tests[@]} -gt 0 ]]; then
    echo "✗ FAILED (${#failed_tests[@]}/${total_tests}):"
    for test in "${failed_tests[@]}"; do
        echo "  • Test ${test}"
    done
    echo ""
fi

# Calculate and display success rate
success_rate=$(( (${#passed_tests[@]} * 100) / total_tests ))
echo "Success rate: ${success_rate}% (${#passed_tests[@]}/${total_tests} tests passed)"

# Exit with non-zero if any tests failed
if [[ ${#failed_tests[@]} -gt 0 ]]; then
    exit 1
fi