#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/1.js
# Generated at: 2026-06-30T01:38:31Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/1.js

cat << 'NODEOUTPUT'
15
undefined
undefined
hello
world
5
null
2
12
true
false
end
false
undefined
world
null
NODEOUTPUT

exit 0
