#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/10.js
# Generated at: 2026-06-30T01:39:13Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/10.js

cat << 'NODEOUTPUT'
171
undefined
undefined
lambda
mu
2048
null
864
480
true
false
>>>>>
true
undefined
mu
null
NODEOUTPUT

exit 0
