#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/11.js
# Generated at: 2026-06-30T01:39:15Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/11.js

cat << 'NODEOUTPUT'
93.92530000000001
4.121951219512194
21.74
35.1
40.5
NODEOUTPUT

exit 0
