#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/12.js
# Generated at: 2026-06-30T01:39:17Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/12.js

cat << 'NODEOUTPUT'
17.539709090909092
3.243913857677903
51.700365
10.210202101859336
37.12396694214876
NODEOUTPUT

exit 0
