#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/13.js
# Generated at: 2026-06-30T01:39:20Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/13.js

cat << 'NODEOUTPUT'
49.77020601700458
5.272154192140264
7.308441454384706
93.66288717163611
7.0976138682553644
NODEOUTPUT

exit 0
