#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/14.js
# Generated at: 2026-07-02T03:14:35Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/14.js

cat << 'NODEOUTPUT'
129.2
94.2
82.41666666666666
NODEOUTPUT

exit 0
