#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/15.js
# Generated at: 2026-07-02T03:14:37Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/15.js

cat << 'NODEOUTPUT'
129
160
22.125
NODEOUTPUT

exit 0
