#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/16.js
# Generated at: 2026-07-02T03:14:39Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/16.js

cat << 'NODEOUTPUT'
94.5
158.6
162.77272727272728
NODEOUTPUT

exit 0
