#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/17.js
# Generated at: 2026-07-02T03:14:42Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/17.js

cat << 'NODEOUTPUT'
57.875
283.6363636363636
31.303030303030308
NODEOUTPUT

exit 0
