#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/18.js
# Generated at: 2026-07-02T05:16:51Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/18.js

cat << 'NODEOUTPUT'
24
61
97
NODEOUTPUT

exit 0
