#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/19.js
# Generated at: 2026-07-02T05:16:53Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/19.js

cat << 'NODEOUTPUT'
63.875
287.6363636363636
33.80303030303031
NODEOUTPUT

exit 0
