#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/2.js
# Generated at: 2026-06-30T01:38:34Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/2.js

cat << 'NODEOUTPUT'
4
undefined
undefined
value1
value2
100
null
50
18
true
false
---
true
undefined
value2
null
NODEOUTPUT

exit 0
