#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/raw/dev/._/._/._/tests/basics/20.js
# Generated at: 2026-08-17T20:04:56Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/raw/dev/._/._/._/tests/basics/20.js

cat << 'NODEOUTPUT'
123321
NODEOUTPUT

exit 0
