#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/raw/dev/._/._/._/tests/basics/21.js
# Generated at: 2026-08-17T20:04:57Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/raw/dev/._/._/._/tests/basics/21.js

cat << 'NODEOUTPUT'
56788512
3224935095174144
NODEOUTPUT

exit 0
