#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/raw/dev/._/._/._/tests/basics/22.js
# Generated at: 2026-08-17T21:35:57Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/raw/dev/._/._/._/tests/basics/22.js

cat << 'NODEOUTPUT'
150
3375000
11390625000000
NODEOUTPUT

exit 0
