#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/raw/dev/._/._/._/tests/basics/22.js
# Generated at: 2026-08-17T20:04:57Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/raw/dev/._/._/._/tests/basics/22.js

cat << 'NODEOUTPUT'
56788512
1.8313926535151802e+23
3.353999051349373e+46
NODEOUTPUT

exit 0
