#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/dev/._/._/._/tests/basics/23.js
# Generated at: 2026-08-18T13:24:09Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/dev/._/._/._/tests/basics/23.js

cat << 'NODEOUTPUT'
42
100
999
john
jane
true
false
NODEOUTPUT

exit 0
