#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/dev/._/._/._/tests/basics/24.js
# Generated at: 2026-08-18T13:24:13Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/dev/._/._/._/tests/basics/24.js

cat << 'NODEOUTPUT'
10
20
15
40
55
45
18.333333333333332
3
NODEOUTPUT

exit 0
