#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/dev/._/._/._/tests/basics/25.js
# Generated at: 2026-08-18T13:24:18Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/dev/._/._/._/tests/basics/25.js

cat << 'NODEOUTPUT'
10
3.14
hello
true
null
undefined
42
world
false
NODEOUTPUT

exit 0
