#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/dev/._/._/._/tests/basics/26.js
# Generated at: 2026-08-18T13:24:26Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/dev/._/._/._/tests/basics/26.js

cat << 'NODEOUTPUT'
5
text
true
null
undefined
100
updated
false
null
undefined
150
final
true
NODEOUTPUT

exit 0
