#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/dev/._/._/._/tests/basics/27.js
# Generated at: 2026-08-18T13:24:38Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/dev/._/._/._/tests/basics/27.js

cat << 'NODEOUTPUT'
100
25
7
3
272
1188
21.22895622895623
323178.923681257
6861803.22495059
15342980.152482549
325744000.5257189
-359841671356.54816
47084343497942.32
980.1524825487286
977232001.5771568
1.6988921185911166e+25
NODEOUTPUT

exit 0
