#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/dev/._/._/._/tests/basics/29.js
# Generated at: 2026-08-19T13:32:08Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/dev/._/._/._/tests/basics/29.js

cat << 'NODEOUTPUT'
3
-12
-12
-5
7
-7
-5
-1
-2.5
NODEOUTPUT

exit 0
