#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/3.js
# Generated at: 2026-06-30T01:38:37Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/3.js

cat << 'NODEOUTPUT'
12
undefined
undefined
test
data
42
null
18
24
true
false
separator
false
undefined
data
null
NODEOUTPUT

exit 0
