#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/dev/._/._/._/tests/basics/31.js
# Generated at: 2026-08-19T15:19:07Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/dev/._/._/._/tests/basics/31.js

cat << 'NODEOUTPUT'
8
20
25
25
1
14
NODEOUTPUT

exit 0
