#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/dev/._/._/._/tests/basics/32.js
# Generated at: 2026-08-19T15:19:11Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/dev/._/._/._/tests/basics/32.js

cat << 'NODEOUTPUT'
48
4
5
2.5
39
7.75
50
25
NODEOUTPUT

exit 0
