#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/4.js
# Generated at: 2026-06-30T01:38:42Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/4.js

cat << 'NODEOUTPUT'
23
undefined
undefined
alpha
beta
77
null
33
62
true
false
divider
true
undefined
beta
null
NODEOUTPUT

exit 0
