#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/5.js
# Generated at: 2026-06-30T01:38:51Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/5.js

cat << 'NODEOUTPUT'
35.31684981684982
undefined
gamma
delta
null
122.6969696969697
false
33.332069110830176
0.6782106782106782
8.861909201344746
54.348751466398525
23.502685284640172
0.37471358900891816
1.9781529294935467
98.69468423443891
312.96296296296293
4.986901986901987
null
NODEOUTPUT

exit 0
