#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/6.js
# Generated at: 2026-06-30T01:38:55Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/6.js

cat << 'NODEOUTPUT'
31
undefined
undefined
gamma
delta
144
null
81
107
true
false
/////
true
undefined
delta
null
NODEOUTPUT

exit 0
