#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/7.js
# Generated at: 2026-06-30T01:38:59Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/7.js

cat << 'NODEOUTPUT'
79
undefined
undefined
epsilon
zeta
256
null
128
55
true
false
*****
false
undefined
zeta
null
NODEOUTPUT

exit 0
