#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/8.js
# Generated at: 2026-06-30T01:39:03Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/8.js

cat << 'NODEOUTPUT'
78
undefined
undefined
eta
theta
512
null
216
157
true
false
+++++
true
undefined
theta
null
NODEOUTPUT

exit 0
