#!/usr/bin/env bash
# Cached node output - Generated by runtest.sh --save
# Original file: /home/new/raw/._/._/._/._/tests/basics/9.js
# Generated at: 2026-06-30T01:39:08Z

# This file contains pre-captured node output
# Execute it to get the same output as running: node /home/new/raw/._/._/._/._/tests/basics/9.js

cat << 'NODEOUTPUT'
138
undefined
undefined
iota
kappa
1024
null
432
253
true
false
=====
false
undefined
kappa
null
NODEOUTPUT

exit 0
